//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTrade.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyTrade.Resources.Translator", typeof(Translator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქონლის ნაშთი.
        /// </summary>
        public static string BalanceOfGoods {
            get {
                return ResourceManager.GetString("BalanceOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მყიდველები.
        /// </summary>
        public static string Buyers {
            get {
                return ResourceManager.GetString("Buyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კომპანიის რეკვიზიტები.
        /// </summary>
        public static string CompanyRequisites {
            get {
                return ResourceManager.GetString("CompanyRequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქონელი.
        /// </summary>
        public static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლის სახელი ან პაროლი არასწორია!.
        /// </summary>
        public static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შესვლა.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გასვლა.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მთავარი.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლი.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქონლის რეალიზაცია.
        /// </summary>
        public static string RealizationGoods {
            get {
                return ResourceManager.GetString("RealizationGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რეალიზებული საქონელი.
        /// </summary>
        public static string RealizedGoods {
            get {
                return ResourceManager.GetString("RealizedGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მიღებული საქონელი.
        /// </summary>
        public static string ReceivedGoods {
            get {
                return ResourceManager.GetString("ReceivedGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქონლის მიღება.
        /// </summary>
        public static string ReceiveGoods {
            get {
                return ResourceManager.GetString("ReceiveGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლის სახელი და პაროლი აუცილებელია!.
        /// </summary>
        public static string RequiredUsernameAndPassword {
            get {
                return ResourceManager.GetString("RequiredUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაიარეთ ავტორიზაცია.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თანამშრომლები.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომწოდებლები.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლის სახელი.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებლები.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საწყობები და მაღაზიები.
        /// </summary>
        public static string WarehousesAndShops {
            get {
                return ResourceManager.GetString("WarehousesAndShops", resourceCulture);
            }
        }
    }
}
